### ISSUE TITLE
Errors when I create issues

### ISSUE THREAD

**Issue by jlestel** [samchen2009/ekanban#9]
Hello,

I want to submit you some errors.

1) When i create an issue, i got the following error : 
NoMethodError (undefined method `issue_status' for #<Issue:0x007ffc7bea5db0>):
  app/controllers/issues_controller.rb:137:in`create'

---

2) When i try to display Kanbans, i have this error. I change this line in kanban.rb  at line 283 :
id = CustomField.find_by_name("WIP limit").id
to 
id = "my-wip-limit"

This is the end of the stack of the error :
Started GET "/projects/test/kanbans" for 127.0.0.1 at 2013-03-15 16:55:50 +0100
Processing by KanbansController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: jlestel (id=71)
  Rendered plugins/ekanban/app/views/kanbans/index.html.haml within layouts/base (35.6ms)
Completed 500 Internal Server Error in 310ms

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2:   %span Your current wip:
    3:   = link_to "#{User.current.wip} ", my_page_path(), :id => "my-wip"
    4:   %span  Limit:
    5:   = link_to "#{User.current.wip_limit} ", edit_user_path(User.current.id), :id => "my-wip-limit"
    6:   = link_to l(:label_kanban_new), new_project_kanban_path(@project.id), :class => 'icon icon-add'
    7: %h2 Kanbans
    8: 
  plugins/ekanban/app/models/kanban.rb:283:in`wip_limit'

---

3) When i try to update a Kanban in Kanbans view, i got this error :
NoMethodError (undefined method `id' for nil:NilClass):
  plugins/ekanban/app/controllers/kanban_cards_controller.rb:40:in`update'

---

4) When i try to display Kanban report, i got this error : 
Started GET "/kanban_reports/index?project_id=220" for 127.0.0.1 at 2013-03-15 17:26:43 +0100
Processing by KanbanReportsController#index as HTML
  Parameters: {"project_id"=>"220"}
  Current user: jlestel (id=71)
Completed 500 Internal Server Error in 17ms

NoMethodError (undefined method `id' for nil:NilClass):
  plugins/ekanban/app/controllers/kanban_reports_controller.rb:130:in`statuses'
  plugins/ekanban/app/controllers/kanban_reports_controller.rb:23:in `index'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:4:in`send_action'

---

Thanks !

**Comment by samchen2009** [comment]
Hi, Thanks for reporting these, I knew that there're still many bugs, that's why I shared the code here and hope somebody to help to improve it :-), feel free to modify it and "pull request" if any. 

Back to the 4 issues: 
1. I did find some 'no method' errors inside redmine under developement mode, (but it rarely happens in 'production' mode).  So I guess it's something to do with the dependencies and rails object cache, but I still need more time to figure it out.
2. I wonder why you like to do this? "WIP Limit" is a field in database (added by ekanban), and "my-wip-limit' is just the html element id.
3. I came cross this issue before, see https://github.com/samchen2009/ekanban/commit/26d8f65a302fe7d5b40651aa7b87749efe4b7365, with this change, I never hit it. Could you provide more information, like the parameters at that point?
4. Sorry, this is definitely a bug, I hard code the kanban stage name there, so once you have difference name, it'll crash, I'll try to fix it soon, before that, you could change your kanban stage name.

**Comment by samchen2009** [comment]
Solved #4 in https://github.com/samchen2009/ekanban/commit/95eaa857892bf7685616473398ff61b6d5084d27

**Comment by jlestel** [comment]
Hi, 

Thanks for resolving points 3. I resolve point 2 adding manually the custom field for Users.

I still got error when i create issues : 
Started GET "/projects/test-julien/issues/new" for 127.0.0.1 at 2013-03-19 18:39:04 +0100
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"test-julien"}
  Current user: jlestel (id=71)
  Rendered issues/_form_custom_fields.html.erb (6.3ms)
  Rendered issues/_attributes.html.erb (25.5ms)
  Rendered issues/_form.html.erb (41.3ms)
  Rendered attachments/_form.html.erb (2.0ms)
  Rendered issues/new.html.erb within layouts/base (47.5ms)
Completed 200 OK in 110ms (Views: 64.4ms | ActiveRecord: 16.6ms)
[2013-03-19 18:39:04] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
Started POST "/projects/test-julien/issues" for 127.0.0.1 at 2013-03-19 18:39:11 +0100
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4YpXjg0ifL3WIcS8yaXuMHhjOnfNrVGTQ/R1lkuVdFk=", "issue"=>{"is_private"=>"0", "tracker_id"=>"1", "subject"=>"new bug", "description"=>"new bug", "status_id"=>"1", "priority_id"=>"4", "assigned_to_id"=>"", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2013-03-19", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0"}, "attachments"=>{"1"=>{"description"=>""}}, "commit"=>"Créer", "project_id"=>"test-julien"}
  Current user: jlestel (id=71)
Completed 500 Internal Server Error in 67ms

NoMethodError (undefined method `issue_status' for #<Issue:0x007facc7575eb0>):
  app/controllers/issues_controller.rb:137:in`create'

---

And when i update an existing issue :

Started PUT "/issues/2330" for 127.0.0.1 at 2013-03-19 18:37:50 +0100
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4YpXjg0ifL3WIcS8yaXuMHhjOnfNrVGTQ/R1lkuVdFk=", "issue"=>{"is_private"=>"0", "project_id"=>"220", "tracker_id"=>"1", "subject"=>"bugance setsetest", "description"=>"bugance test set ", "status_id"=>"1", "priority_id"=>"4", "assigned_to_id"=>"", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2013-03-18", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "lock_version"=>"0"}, "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "notes"=>"testes t", "attachments"=>{"1"=>{"description"=>""}}, "last_journal_id"=>"", "commit"=>"Soumettre", "id"=>"2330"}
  Current user: jlestel (id=71)
Completed 500 Internal Server Error in 79ms

NoMethodError (undefined method `kanban_pane' for nil:NilClass):
  app/models/issue.rb:884:in`block in save_issue_with_child_records'
  app/models/issue.rb:871:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:171:in`update'

Thanx again !

**Comment by samchen2009** [comment]
"NoMethodError (undefined method issue_status' for #Issue:0x007facc7575eb0):
app/controllers/issues_controller.rb:137:increate'"

I think this occured on kanban.rb::validate_kanban_card_new, I often come into such kind of "NoMethodError" in development, I knew it's something to do with ekanban (I extend some redmine models) and the rails object cache because I never meet it in production mode. Did you have a try production mode?

**Comment by samchen2009** [comment]
"NoMethodError (undefined method kanban_pane' for nil:NilClass):
app/models/issue.rb:884:inblock in save_issue_with_child_records'
app/models/issue.rb:871:in save_issue_with_child_records'
app/controllers/issues_controller.rb:171:inupdate'" 

May crash inside kanban.rb::validate_kanban_card_update, you could add some log there to check whether card is nil? I guess one issue was created without corresponding card is created.

**Comment by samchen2009** [comment]
I guess the issues above should be solved as #16, please have a try the latest code.

**Comment by jlestel** [comment]
In production mode, I still get this error when i create an issue without any assignee :

NoMethodError (undefined method `wip' for nil:NilClass):
  app/controllers/issues_controller.rb:137:in`create'

---

On an existing issue, i get this error when there's no assignee : 

NoMethodError (undefined method `member_of?' for nil:NilClass):
  app/models/issue.rb:884:in`block in save_issue_with_child_records'
  app/models/issue.rb:871:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:171:in`update'

If i assign someone, i got this one :

  Rendered mailer/_issue.text.erb (3.1ms)
  Rendered mailer/issue_edit.text.erb within layouts/mailer (5.3ms)
  Rendered mailer/_issue.html.erb (0.3ms)
  Rendered mailer/issue_edit.html.erb within layouts/mailer (1.4ms)
Completed 500 Internal Server Error in 226ms

NoMethodError (undefined method `name' for nil:NilClass):
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  app/models/issue.rb:886:in `block in save_issue_with_child_records'
  app/models/issue.rb:871:in`save_issue_with_child_records'
  app/controllers/issues_controller.rb:171:in `update'

**Comment by samchen2009** [comment]
The "NoMethodError (undefined method name' for nil:NilClass)" is the same as #16, and I think it's fixed by latest commit 1d4deeb5d042db4ec99692f21b15c334abb23a2d, could you confirm it?

**Comment by Mirnoth** [comment]
The "NoMethodError" seems not to be fixed. I get this error:
Completed 500 Internal Server Error in 521ms

NoMethodError (undefined method `[]' for nil:NilClass):
  lib/redmine/hook.rb:61:in`send'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:153:in`call_hook'
  app/controllers/issues_controller.rb:144:in `create'

**Comment by samchen2009** [comment]
The error should happen in the function below, context is nil ...  could you check why ?

def controller_issues_new_after_save(context={})
         card = KanbanCard.build(context[:issue], context[:journal])
         true
end

**Comment by Mirnoth** [comment]
I tried to test it, but i am not familiar with Ruby. I have not found the issue.

**Comment by Blacksus** [comment]
I got exactly the same error when I tried to submit an issue....

Log:
Completed 500 Internal Server Error in 78ms

NoMethodError (undefined method `wip' for nil:NilClass):
  app/controllers/issues_controller.rb:141:in`create'

**Comment by raels** [comment]
To get things even partially working, I had to manually create a CustomField for the user called "WIP limit", as an integer, which I defaulted to 1.  I was then able to see the KanBan's instead of getting server errors.  This solved at least problem number 2 above for me.
